apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./listener-srv/infra/rabbitmq-depl.yaml
      - ./process-srv/infra/redis.depl.yaml
      - ./listener-srv/infra/listeners-depl.yaml
      - ./process-srv/infra/processors-depl.yaml
      - ./process-srv/infra/processors-hpa.yaml
      - ./notify-srv/infra/notify-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: falupi22/listener-srv
      context: listener-srv
      docker:
        dockerfile: ./DockerFile
      sync:
        manual:
          - src: 'backend/listener-srv/**/*.ts'
            dest: .
    - image: falupi22/process-srv
      context: process-srv
      docker:
        dockerfile: ./DockerFile
      sync:
        manual:
          - src: 'backend/process-srv/**/*.ts'
            dest: .
    - image: falupi22/notify-srv
      context: notify-srv
      docker:
        dockerfile: ./DockerFile
      sync:
        manual:
          - src: 'backend/notify-srv/**/*.ts'
            dest: .
