apiVersion: apps/v1
kind: Deployment
metadata:
    name: listeners-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: listeners
    template:
        metadata:
            labels:
                app: listeners
        spec:
            containers:
                - name: listeners
                  image: falupi22/listener-srv
                  resources:
                      requests:
                          cpu: '200m'
                      limits:
                          cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
    name: listeners-srv
spec:
    type: NodePort
    selector:
        app: listeners
    ports:
        - name: listeners
          protocol: TCP
          port: 4001
          targetPort: 4001
          nodePort: 30000
