version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
        MODE: development
    command: yarn start