apiVersion: apps/v1
kind: Deployment
metadata:
    name: processors-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: processors
    template:
        metadata:
            labels:
                app: processors
        spec:
            containers:
                - name: processors
                  image: falupi22/process-srv
                  resources:
                      requests:
                          cpu: '200m'
                          memory: '256Mi'
                      limits:
                          cpu: '500m'
                          memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
    name: processors-cluster-ip-srv
spec:
    type: ClusterIP
    selector:
        app: processors
    ports:
        - name: processors
          protocol: TCP
          port: 4001
          targetPort: 4001
