apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rabbitmq
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
                - name: rabbitmq
                  image: rabbitmq:3-management # Includes the management UI
                  ports:
                      - containerPort: 5672 # AMQP port
                      - containerPort: 15672 # Management UI port
                  env:
                      - name: RABBITMQ_DEFAULT_USER
                        value: 'admin'
                      - name: RABBITMQ_DEFAULT_PASS
                        value: 'password'
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-cluster-ip-srv
spec:
    type: ClusterIP
    selector:
        app: rabbitmq
    ports:
        - port: 5672
          targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-srv
spec:
    type: NodePort
    selector:
        app: rabbitmq
    ports:
        - port: 15672
          targetPort: 15672
          nodePort: 31672
